#!/usr/bin/env python3
"""Reuse fleetctl's client renderer without changing fleet boot selection."""
import argparse
import importlib.util
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--fleet-scripts', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location('fleetctl', args.fleet_scripts / 'fleetctl.py')
    fleet = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(fleet)
    source = Path(__file__).with_name('deepseek-v41-exl3-client.yaml')
    lines = fleet.client_env_lines(str(source))
    lines.append(('OPENAI_COMPAT_REASONING_DIALECT', fleet.get(str(source), 'reasoning_dialect')))
    header = [
        '# GENERATED by deploy/render_aide_env.py using gx10-fleet client_env_lines.',
        '# Source: ventus-deepseek-v41-exl3/deploy/deepseek-v41-exl3-client.yaml.',
        '# Experiment only; fleet boot selection is unchanged. DO NOT HAND-EDIT.',
    ]
    args.output.write_text('\n'.join(header + [f'{k}={v}' for k, v in lines]) + '\n',
                           encoding='utf-8', newline='\n')


if __name__ == '__main__':
    main()
